@startuml
left to right direction
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 40
hide empty members

namespace FileSurfer {
    class Program
    class FileSurferSettings
}

namespace FileSurfer.Models {
    interface IFileSystemEntry
    class FileEntry
    class DirectoryEntry
    class "UndoRedoHandler<T>"
    class FileOperationResult
    
    namespace FileOperations {
	interface IFileOperationHandler
	class ArchiveManager
	class ClipboardManager
	class WindowsFileOperationHandler
	
	namespace Undoable {
	    interface IUndoableFileOperation
	    class CopyFilesTo
	    class DuplicateFiles
	    class MoveFilesTo
	    class MoveFilesToTrash
	    class NewDirAt
	    class NewFileAt
	    class RenameFiles
	    class FlattenFolder
	}
    }

    namespace VersionControl {
	interface IVersionControl
	class GitVersionControlHandler
    }
    
    namespace Shell {
	class WindowsFileRestorer
	class WindowsFileProperties
	interface IShellHandler
	class WindowsShellHandler
    }

    namespace FileInformation {
	interface IFileInfoProvider
	class IconProvider
	class FileNameGenerator
	class WindowsFileInfoProvider
    }
}

namespace FileSurfer.ViewModels {
    class MainWindowViewModel
    class FileSystemEntryViewModel
}

namespace FileSurfer.Views {
    class MainWindow
    class SettingsWindow
    class ErrorDialog
    class ConfirmationDialog
}


FileSurfer.ViewModels -r-> FileSurfer.Models : interact with
FileSurfer.ViewModels -d--> FileSurfer.Views : serve data to

FileSurfer.Models.Shell.WindowsShellHandler ..|> FileSurfer.Models.Shell.IShellHandler
FileSurfer.Models.FileInformation.WindowsFileInfoProvider ..|> FileSurfer.Models.FileInformation.IFileInfoProvider
FileSurfer.Models.VersionControl.GitVersionControlHandler ..|> FileSurfer.Models.VersionControl.IVersionControl
FileSurfer.Models.FileOperations.WindowsFileOperationHandler ..|> FileSurfer.Models.FileOperations.IFileOperationHandler

FileSurfer.Models.FileEntry ..d|> FileSurfer.Models.IFileSystemEntry 
FileSurfer.Models.DirectoryEntry ..l|> FileSurfer.Models.IFileSystemEntry
@enduml